### Muhamad Rizky Nilzamyahya 2009106029

# POSTTEST 4

In [105]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [106]:
df = pd.read_csv('anime.csv')
df

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12296     28977                                           Gintama°   
12297      9253                                        Steins;Gate   
12298      9969                                      Gintama&#039;   
12299     32935  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...   
12300     11061                             Hunter x Hunter (2011)   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12296  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
12297                                   Sci-Fi, Thriller     TV       24   
12298  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
12299             Comedy, Drama, School, Shounen, Sports     TV       10   
12300            Action, Adventure, Shounen, Super Power     TV      148   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12296    9.25   114262  
12297    9.17   673572  
12298    9.16   151266  
12299    9.15    93351  
12300    9.13   425855  

[12301 rows x 7 columns]

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12301 entries, 0 to 12300
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12301 non-null  int64  
 1   name      12301 non-null  object 
 2   genre     12239 non-null  object 
 3   type      12276 non-null  object 
 4   episodes  12301 non-null  object 
 5   rating    12071 non-null  float64
 6   members   12301 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.8+ KB


In [108]:
df.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [109]:
df.shape

(12301, 7)

# Training set : Testing set = 70 : 30

In [110]:
# Subset feature dan target
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

# Buat kelas train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [111]:
print("Dimensi X_train:", X_train.shape)
print("Dimensi X_Test:", X_test.shape)
print("Dimensi y_train:", y_train.shape)
print("Dimensi y_test:", y_test.shape)

Dimensi X_train: (8610, 6)
Dimensi X_Test: (3691, 6)
Dimensi y_train: (8610,)
Dimensi y_test: (3691,)


# Normalisasi data pada salah satu attribute

In [112]:
from sklearn.preprocessing import MinMaxScaler

In [113]:
mss = MinMaxScaler()

In [114]:
x_scaled = mss.fit_transform(
    df[
        ['anime_id','rating','members']
    ]
)

In [115]:
data_normalization = pd.DataFrame(x_scaled)
data_normalization.head()

0         1         2
0  0.934948  0.924370  0.197872
1  0.148091  0.911164  0.782770
2  0.839252  0.909964  0.112689
3  0.267972  0.900360  0.664325
4  0.288710  0.899160  0.149186

# Standarisasi pada dataset

In [116]:
np.std(df)

C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3571: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


anime_id    11455.258854
rating          1.028524
members     55731.784131
dtype: float64

In [117]:
from sklearn.preprocessing import StandardScaler

In [118]:
ss = StandardScaler()

In [119]:
x_scaled2 = ss.fit_transform(
    df[
        ['anime_id','rating','members']
    ]
)

## Cara 1 :

In [120]:
data_standarization = pd.DataFrame(x_scaled2)
data_standarization.head()

0         1          2
0  1.590557  2.814238   3.272272
1 -0.781017  2.707288  13.913148
2  1.302131  2.697566   1.722564
3 -0.419699  2.619784  11.758309
4 -0.357195  2.610062   2.386530

In [121]:
np.std(x_scaled2)

nan

In [122]:
np.mean(x_scaled2)

nan

## Cara 2 :

In [123]:
print("Nilai Data Sebelum scaling : ")
print(
    df[
        ['anime_id','rating','members']
    ]
)

Nilai Data Sebelum scaling : 
       anime_id  rating  members
0         32281    9.37   200630
1          5114    9.26   793665
2         28977    9.25   114262
3          9253    9.17   673572
4          9969    9.16   151266
...         ...     ...      ...
12296     28977    9.25   114262
12297      9253    9.17   673572
12298      9969    9.16   151266
12299     32935    9.15    93351
12300     11061    9.13   425855

[12301 rows x 3 columns]


In [124]:
print("Nilai standar deviasi:\n", np.std(
    df[
        ['anime_id','rating','members']
    ]
))

Nilai standar deviasi:
 anime_id    11455.258854
rating          1.028524
members     55731.784131
dtype: float64


In [125]:
print("\n Nilai Data setelah scaling : ")
print(x_scaled2)
print("Nilai standar deviasi: ", np.std(x_scaled2))


 Nilai Data setelah scaling : 
[[ 1.59055711  2.81423783  3.2722721 ]
 [-0.78101741  2.70728841 13.91314803]
 [ 1.30213063  2.69756574  1.72256396]
 ...
 [-0.3571946   2.61006167  2.38652978]
 [ 1.64764879  2.60033899  1.34735616]
 [-0.2618672   2.58089365  7.31350286]]
Nilai standar deviasi:  nan


# Data Cleaning pada data bernilai null (numeric)

## Cara 1 :

In [126]:
# Melihat data NULL
df.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [127]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

In [128]:
df["rating"] = imputer.fit_transform(df[['rating']])

In [129]:
# Cek data NULL yang dihilangkan
df.isna().sum()

anime_id     0
name         0
genre       62
type        25
episodes     0
rating       0
members      0
dtype: int64

## Cara 2 :

In [130]:
df2 = pd.read_csv('anime.csv')

In [131]:
df2.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [132]:
df2["rating"] = df2["rating"].fillna(df2["rating"].mean())

In [133]:
df2.isna().sum()

anime_id     0
name         0
genre       62
type        25
episodes     0
rating       0
members      0
dtype: int64

# Data Cleaning pada data bernilai null (string)

In [134]:
# Cek data NULL
df.isna().sum()

anime_id     0
name         0
genre       62
type        25
episodes     0
rating       0
members      0
dtype: int64

In [135]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')

In [136]:
df["genre"] = imputer.fit_transform(df[['genre']])

In [137]:
# Cek data NULL yang dihilangkan
df.isna().sum()

anime_id     0
name         0
genre        0
type        25
episodes     0
rating       0
members      0
dtype: int64

In [138]:
df["type"] = imputer.fit_transform(df[['type']])

In [139]:
# Cek data NULL yang dihilangkan
df.isna().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

# Data Cleaning pada data bernilai Duplikat

In [140]:
df[df.duplicated()]

anime_id                                               name  \
12294     32281                                     Kimi no Na wa.   
12295      5114                   Fullmetal Alchemist: Brotherhood   
12296     28977                                           Gintama°   
12297      9253                                        Steins;Gate   
12298      9969                                      Gintama&#039;   
12299     32935  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...   
12300     11061                             Hunter x Hunter (2011)   

                                                   genre   type episodes  \
12294               Drama, Romance, School, Supernatural  Movie        1   
12295  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
12296  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
12297                                   Sci-Fi, Thriller     TV       24   
12298  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
12299             Comedy, Drama, School, Shounen, Sports     TV       10   
12300            Action, Adventure, Shounen, Super Power     TV      148   

       rating  members  
12294    9.37   200630  
12295    9.26   793665  
12296    9.25   114262  
12297    9.17   673572  
12298    9.16   151266  
12299    9.15    93351  
12300    9.13   425855

In [141]:
df.duplicated().sum()

7

In [142]:
df.drop_duplicates(inplace = True)

In [143]:
df[df.duplicated()]

Empty DataFrame
Columns: [anime_id, name, genre, type, episodes, rating, members]
Index: []

In [144]:
df.duplicated().sum()

0

## Ganti tipe data salah satu attribute angka(Encoding)

In [145]:
from sklearn.preprocessing import OrdinalEncoder

In [146]:
df.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [147]:
encoder = OrdinalEncoder()
df["type_encoded"] = encoder.fit_transform(df[["type"]])
df.head(10)

anime_id                                               name  \
0     32281                                     Kimi no Na wa.   
1      5114                   Fullmetal Alchemist: Brotherhood   
2     28977                                           Gintama°   
3      9253                                        Steins;Gate   
4      9969                                      Gintama&#039;   
5     32935  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...   
6     11061                             Hunter x Hunter (2011)   
7       820                               Ginga Eiyuu Densetsu   
8     15335  Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...   
9     15417                           Gintama&#039;: Enchousen   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   
5             Comedy, Drama, School, Shounen, Sports     TV       10    9.15   
6            Action, Adventure, Shounen, Super Power     TV      148    9.13   
7                     Drama, Military, Sci-Fi, Space    OVA      110    9.11   
8  Action, Comedy, Historical, Parody, Samurai, S...  Movie        1    9.10   
9  Action, Comedy, Historical, Parody, Samurai, S...     TV       13    9.11   

   members  type_encoded  
0   200630           0.0  
1   793665           5.0  
2   114262           5.0  
3   673572           5.0  
4   151266           5.0  
5    93351           5.0  
6   425855           5.0  
7    80679           3.0  
8    72534           0.0  
9    81109           5.0

# One hot encoding pada dataset

In [148]:
from sklearn.preprocessing import OneHotEncoder

In [149]:
onehotencoder = OneHotEncoder(sparse = False)

In [150]:
type_encoded2 = onehotencoder.fit_transform(df[["type"]])

In [151]:
df2 = pd.DataFrame(type_encoded2)
df = df.join(df2)
df.head(10)

anime_id                                               name  \
0     32281                                     Kimi no Na wa.   
1      5114                   Fullmetal Alchemist: Brotherhood   
2     28977                                           Gintama°   
3      9253                                        Steins;Gate   
4      9969                                      Gintama&#039;   
5     32935  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...   
6     11061                             Hunter x Hunter (2011)   
7       820                               Ginga Eiyuu Densetsu   
8     15335  Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...   
9     15417                           Gintama&#039;: Enchousen   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   
5             Comedy, Drama, School, Shounen, Sports     TV       10    9.15   
6            Action, Adventure, Shounen, Super Power     TV      148    9.13   
7                     Drama, Military, Sci-Fi, Space    OVA      110    9.11   
8  Action, Comedy, Historical, Parody, Samurai, S...  Movie        1    9.10   
9  Action, Comedy, Historical, Parody, Samurai, S...     TV       13    9.11   

   members  type_encoded    0    1    2    3    4    5  
0   200630           0.0  1.0  0.0  0.0  0.0  0.0  0.0  
1   793665           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
2   114262           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
3   673572           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
4   151266           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
5    93351           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
6   425855           5.0  0.0  0.0  0.0  0.0  0.0  1.0  
7    80679           3.0  0.0  0.0  0.0  1.0  0.0  0.0  
8    72534           0.0  1.0  0.0  0.0  0.0  0.0  0.0  
9    81109           5.0  0.0  0.0  0.0  0.0  0.0  1.0